### ISSUE TITLE
Smooth scrolling is "broken"

### ISSUE THREAD

**Issue by abjorck** [dossierhq/dossierhq#533]
in Chrome on Linux at least - i can barely scroll on the dossier pages with the touchpad, it's like it doesnt move until I release my gesture. So slowly scrolling down while reading basically doesnt work at all and feels very yanky.

Thankfully Firefox seems to ignore the `scroll-behavior: smooth;` :shrug:

**Comment by jonasb** [comment]
Interesting. I don't see that behaviour on Mac.

Could you try this page and see if there's any issue with IntersectionObserver on Linux/Chrome?

https://design.dossierhq.dev/?path=/story/components-scrollable--shadows-none

**Comment by abjorck** [comment]
same behavior there - probably some gnome-crap  
worked fine on my mac/chromium too.

**Comment by abjorck** [comment]
fniss, nevermind, it was the linux-scroll-speed-fix extension
:whistling:
